2024-09-11 20:02:06,865 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Пользователь\PycharmProjects\Homework\Module_12\tests_12_4.py", line 17, in test_run
    runner = rt.Runner(25)
             ^^^^^^^^^^^^^
  File "C:\Users\Пользователь\PycharmProjects\Homework\Module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-11 20:02:06,915 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Пользователь\PycharmProjects\Homework\Module_12\tests_12_4.py", line 9, in test_walk
    runner = rt.Runner('Sergey', -5)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Пользователь\PycharmProjects\Homework\Module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
